### ISSUE TITLE
As a trainer I can choose to login or sign up on the connect 5 platform

### ISSUE THREAD

**Issue by RamyAlshurafa** [techforbetter/connect5#25]
Relates #24 
#### Acceptance criteria:
- [ ] When I'm on " I'm a Connect 5 trainer " page, I want to get a choice of login or sign up to the platform.
- [ ] When I'm on " I'm a Connect 5 trainer" page, I want to see "Welcome trainer" section.
- [ ] When I'm on " I'm a Connect 5 trainer" page, I want to see a header that contains website logo and a button that return me back to " Home landing page ".
