### ISSUE TITLE
As a trainer I can sign up for the connect 5 platforms.

### ISSUE THREAD

**Issue by RamyAlshurafa** [techforbetter/connect5#26]
## As a trainer I can sign up for the connect 5 platforms.
Relates #24 
 #### Acceptance criteria:
- [x] When I'm on " Sign up" page, I want to be able to sign up to Connect 5 platform.
- [x] When I'm on " Sign up" page, I want to get a form to fill in my details.
> Details to fill in: Full Name, Email, Password, Confirm Password
- [x] When I'm on " Sign up" page, and while I fill my information I want a guide of what these inputs must be filled in with.
- [x] When I'm on " Sign up " page, and if I filled something wrong I want to get a message to tell me what's wrong.
- [x] When I type in an email that already exists I get a warning
- [x] When I finish signing up, and everything ok, I want to be redirected to login page
- [x] When I finish signing up, and there's something wrong, In the registration, I want to get an " Error" page

Important functionality to complete for this user story:
- [x] Once successful, user is stored in database in Users table
- [x] error handling for email, name, password inputs in backend 
- [x] form validation via React frontend
