### ISSUE TITLE
As a trainer I want to view my session result in a single page [ Individuals responses ] 

### ISSUE THREAD

**Issue by RamyAlshurafa** [techforbetter/connect5#34]
## As a trainer I want to view my session result in a single page for each session with Individuals responses tab.
Relates #31  
 #### Acceptance criteria:
- [ ] When I'm on "Session result" & "Individuals responses" tab, I would like to get a list of responses, each question, and its answer.
- [ ] When I'm on "Session result" & "Individuals responses" tab, I would like to be able to navigate through the responses.
- [ ] When I'm on "Session result" & "Individuals responses" tab, I would like to know the responses number.

**Comment by thejoefriel** [comment]
This can only be achieved after issues #32 and #34 have been completed
